---
title: "Corrige Data Camp"
author: "Andrés David Noza Mico"
date: "2026-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
puntuaciones <- list.files(path=".", pattern = "\\.txt$", full.names = F, recursive = T)

justificantes <- list.files(path=".",pattern = "\\.pdf$", full.names = F, recursive = TRUE)

puntuaciones
```
Extrae los apellidos del usuario de la ruta del fichero de puntuaciones (strsplit)

```{r}

informacion <- strsplit(puntuaciones,split = "/", fixed = T)

apellidos_nombres_id <- sapply(informacion, function(x) x[2])

apellidos_nombre_lista <- strsplit(apellidos_nombres_id, split = ",",fixed = T)

apellidos_puntuaciones <- sapply(apellidos_nombre_lista, function(x)x[1])

```
Importa el fichero puntos.txt y extrae la puntuación obtenida (readlines).

```{r}
puntos_full_names <- list.files(path = ".", pattern = "\\.txt$", full.names = T, recursive = T)

puntos_lista<- lapply(puntos_full_names,function(x) {readLines(con = x, n= -1)})
```

¿todas las entregas usaron como nombre del fichero de puntos el indicado; puntos.txt ?¿cuántas variantes hay ?. ¿Todas las entregas contienen el fichero de puntos y el justificante de realización del curso ?

```{r}
ficheros_puntos <- lapply(informacion,function(x){x[3]})
ficheros_correctos <- lapply(ficheros_puntos, function(x){grep("puntos.txt",x)})

```

